
=== Open and close

[[open]]
* _sndfile_, <<fileinfo, _fileinfo_>> = *open*(_path_, <<openmode, _openmode_>>, [<<fileinfo, _fileinfo_>>]) +
[small]#Returns the newly created _sndfile_ object followed by its updated _fileinfo_. +
The _fileinfo_ argument is required for the '_raw_' format and/or if _openmode_='_w_' (write)
to specify the file format, the sample rate, and the number of channels.
The format may be specified either: +
pass:[1)] by setting the _fileinfo.code_ field to a valid integer encoding the major format, the 
subformat, and the endianness, or +
pass:[2)] by setting separately the _fileinfo.format_, the _fileinfo.subformat_ and optionally the 
_fileinfo.endianness_ fields with valid literal values. +
In the first case, the fields listed in the second case are not needed, but if present they must
match the values encoded in the _code_ field. +
In both cases, all other fields apart from _fileinfo.samplerate_ and _fileinfo.channels_ are ignored. +
The _fileinfo_ argument must not be passed when opening a non-raw file in 'r' or 'rw' mode. +
Rfr: https://libsndfile.github.io/libsndfile/api.html#open[sf_open].#

[[open_fd]]
* _sndfile_, <<fileinfo, _fileinfo_>> = *open_fd*(_fd_|_fh_, <<openmode, _openmode_>>, [<<fileinfo, _fileinfo_>>], [_closedesc_]) +
[small]#Same as <<open, open>>(&nbsp;), but loads the sound file from an already open file instead of opening one. +
The file can be specified either by passing a valid integer file descriptor (_fd_), or by passing a valid 
http://www.lua.org/manual/5.3/manual.html#pdf-io.open[Lua file handle] (_fh_). +
The optional _closedesc_ parameter (close the file descriptor) deafults to _false_. +
Rfr: https://libsndfile.github.io/libsndfile/api.html#open_fd[sf_open_fd].#

[[close]]
* *close*(_sndfile_) +
[small]#Rfr: https://libsndfile.github.io/libsndfile/api.html#close[sf_close].#

The current, updated, <<fileinfo, _fileinfo_>> (_SF_INFO_) table for a _sndfile_ object can be
retrieved at any time with the following function:

[[get_fileinfo]]
* <<fileinfo, _fileinfo_>> = *get_fileinfo*(_sndfile_) +
[small]#Rfr: https://libsndfile.github.io/libsndfile/command.html#sfc_get_current_sf_info[SFC_GET_CURRENT_SF_INFO].#

Alternatively, the individual <<fileinfo, _fileinfo_>> attributes can be retrieved with the following methods of the _sndfile_ object:

* <<format, _format_>> = _sndfile_++++*:format*( )
* <<subformat, _subformat_>> = _sndfile_++++*:subformat*( )
* <<endianness, _endianness_>> = _sndfile_++++*:endianness*( )
* _integer_ = _sndfile_++++*:code*( )
* _integer_ = _sndfile_++++*:samplerate*( )
* _integer_ = _sndfile_++++*:channels*( )
* _integer_ = _sndfile_++++*:frames*( )
* _integer_ = _sndfile_++++*:sections*( )
* _boolean_ = _sndfile_++++*:seekable*( )


////
[[]]
* **(_sndfile_) +
[small]#Rfr: https://libsndfile.github.io/libsndfile/api.html#[sf_].#

[[]]
* **(_sndfile_) +
[small]#Rfr: https://libsndfile.github.io/libsndfile/command.html#sfc_[].#

////
