
default: build

build:

install:

uninstall:

clean :
	@-rm -f *.txt
	@-rm -f sine.wav
	@-rm -f rand.wav
	@-rm -f output.wav
	@-rm -f gsm610.wav
	@-rm -f imaadpcm.wav
	@-rm -f msadpcm.wav
	@-rm -f pcm16.wav
	@-rm -f pcmu8.wav
	@-rm -f gsm610.w64
	@-rm -f imaadpcm.w64
	@-rm -f msadpcm.w64
	@-rm -f pcm16.w64
	@-rm -f pcmu8.w64

cleanall: clean

backup: clean

